name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/orangeHRM.cy.js
          browser: firefox
      
      - name : Copy Test execution videos and screenshots
        run : 
        mkdir pubic
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots

      -name : Merge test Reports
       run : npm run combine:report

       -name : Generate HTML report
        run : npm run generate:report
