name: Cypress tests
on: push
    branches:
      - 'main'

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/orangeHRM.cy.js
          browser: firefox
          continue-on-error: true

    - name: Copy test execution videos
      run: |
        mkdir public
        cp -r cypress/videos public/videos

    - name: Merge test results into one
      run: npm run report:merge
    - name: Generate HTML report
      run: npm run report:generate
